# Generated by Django 5.0.7 on 2024-07-31 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_created_by_alter_event_total_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['created_at']},
        ),
    ]
