# Generated by Django 5.1 on 2024-08-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventsignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsignup',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
