# Generated by Django 5.1 on 2024-08-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventsignup_is_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsignup',
            options={'ordering': ['signup_date']},
        ),
        migrations.RemoveField(
            model_name='eventsignup',
            name='is_verified',
        ),
    ]
