# Generated by Django 5.1 on 2024-08-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_eventsignup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ending_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='event',
            name='starting_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(),
        ),
    ]
