# Generated by Django 5.1 on 2024-08-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_ending_time_event_starting_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ending_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='starting_time',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
