# Generated by Django 5.1 on 2024-08-15 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['created_at'], 'verbose_name': 'List', 'verbose_name_plural': 'Lists'},
        ),
        migrations.AlterModelOptions(
            name='eventsignup',
            options={'ordering': ['signup_date'], 'verbose_name': 'Registration', 'verbose_name_plural': 'Registrations'},
        ),
    ]
