# Generated by Django 5.1.2 on 2024-11-30 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_options_alter_eventsignup_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('google_map_link', models.URLField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.location'),
        ),
    ]
