# Generated by Django 5.1.2 on 2024-12-02 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_event_options_alter_eventsignup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='events.event'),
        ),
    ]
