# Generated by Django 5.1.2 on 2024-12-05 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_banner_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignup',
            name='event',
            field=models.ForeignKey(limit_choices_to={'is_verified': True}, on_delete=django.db.models.deletion.PROTECT, to='events.event'),
        ),
    ]
