# Generated by Django 5.1.2 on 2024-12-06 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_eventsignup_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventsignup',
            name='event',
            field=models.ForeignKey(limit_choices_to={'status': 'ACTIVE'}, on_delete=django.db.models.deletion.PROTECT, to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventsignup',
            name='user',
            field=models.ForeignKey(limit_choices_to={'status': 'ACTIVE'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
