# Generated by Django 5.1.4 on 2024-12-07 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_category_event_categorty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='categorty',
            new_name='category',
        ),
    ]
