# Generated by Django 5.1.2 on 2024-11-26 18:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_alter_usertoken_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserToken',
            new_name='UserActivationToken',
        ),
    ]
