# Generated by Django 5.1.2 on 2024-11-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preferences", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailtemplate",
            name="name",
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("EVENT_SIGNUP", "Event Signup"),
                    ("ACCOUNT_ACTIVATION", "Account Activation"),
                    ("USER_RESET_PASSWORD", "User Reset Password"),
                ],
                default="This is a sample email template.",
                max_length=50,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
